name: unicore_data
version: '1.0.0'
config-version: 2

profile: unicore_data

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]
macro-paths: ["macros"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  unicore_data:
    sources:
      +schema: ""
    marts:
      +materialized: table
      +schema: marts

seeds:
  unicore_data:
    +schema: ""
